### ISSUE TITLE
Editor requests for information about taxonomic changes and lower level taxonomic resolution

### ISSUE THREAD

**Issue by sean-rohan-NOAA** [afsc-gap-products/esrindex#3]
Request for information about taxonomic changes.

Corals/Sponges/Sea Stars - too many to list what the old vs new list is in the ESR. Could you add some language in ESR (1 sentence) referencing GAP protocols that changed resulting in additional species added to ESR categories this year. If possible, some qualitative text describing major trends in the subcategories of corals/sponges would be helpful, if available, to relate to potential trends in rockfish.

**Comment by Ned-Laman-NOAA** [comment]
A question and a thought.
Is this one time language that needs to be inserted in this year's ESR chapters or are you looking for some sort of more general statement that says taxonomy changes, species of interest change, and that's reflected in the results?
The thought is that many of the taxonomic comp. changes we made this year were result of several different processes converging and should be one time affairs. 
E.g., Upon review it became clear for the historic sea star/echinoderm group that the Gulf/Aleutian assemblage included several taxa that weren't ecological analogs of one another (e.g., cucumbers and basket stars combined with Asteroidea) and eliminating them from the group had the added advantage of aligning with the sea star assemblage used in the Eastern Bering. Basically, coming to this conclusion confirmed what we suspected which was that the underlying assumptions that have been in place for constructing these chapters for the last decade and more needed to be re-checked.
Similarly, for sponges, using a simple range of RACE species code numbers (91000-91999) was not inclusive of other added sponge taxa that show up in the 95000 code series.
The coral conversation is ongoing and I need to touch base again with @SarahFriedman-NOAA to figure out the final list of animals for this one.

**Comment by sean-rohan-NOAA** [comment]
Curious to hear how folks want to approach it. My impression is that this
could be a one-time statement about the changes and rationale that would be
included in the Methodological Changes section.

Regardless, there would still need to be a recurring description of the
composition of the assemblages.
