### ISSUE TITLE
Taxonomic discrepancies in invert groups

### ISSUE THREAD

**Issue by SarahFriedman-NOAA** [afsc-gap-products/esrindex#7]
### Issue
I have been working on automating the selection of species codes for the different invertebrate groupings we include in the ecosystem status reports. While we have always had some discrepancies between the taxonomy of these groups and what we functionally include, I am finding some inconsistencies in the way we have categorized some species codes. For example, we currently include a few brittle stars in our "sea star" assemblage (species codes 80018, 81930) but not all brittle stars that we have species codes for in the database (n = 63). Likewise, we include a few ctenophore species codes in our "jellyfish" grouping, but not all species codes for ctenophores in our database. I don't believe these will make massive changes to the outcome and trends for each group, but I do think it is worthwhile to come up with a consistent protocol for what we decide to include in each group, whether it be taxonomic, functional, or some combination of the two. 

### Potential solution
I have compiled the [proposed changes](https://github.com/user-attachments/files/17924098/esrindex_group_changes.csv) for each group to create some consistency in these decisions. I am happy to discuss further, but I figured this would be a decent jumping off place for the ESR team (@ThaddaeusBuser-NOAA @sean-rohan-NOAA @smcdermo ).

**Comment by sean-rohan-NOAA** [comment]
Thanks for catching this and compiling the list of proposed changes, @SarahFriedman-NOAA. From chatting with you and @ThaddaeusBuser-NOAA , it sounds like the discrepancies are a result of species codes mistakenly being left in or excluded when the code lists were revised earlier this year and that the composition of each group was based on both taxonomic and functional considerations.

Based on those considerations and the inconsistencies flagged in the proposed changes spreadsheet, does this seem correct?

1. Sea stars: Remaining brittle stars (80018, 81930) will be removed.
2. Corals: Missing corals (41000, 41099, 44116) will be added and Cavernularia vansyoci (41106) will be removed.
3. Sea pens: Cavernularia vansyoci (41106) will be added.
4. Jellyfish: Ctenophores will be removed.
5. Eelpouts: Gibbonsia metzi (24404) will be removed.

**Comment by SarahFriedman-NOAA** [comment]
This sums it up nicely. Thanks, Sean!
